comment:
  header: Hello @{{ issue.user.login }}
  footer: "\
    ---\n\n
    > This is an automated comment created by the [peaceiris/actions-label-commenter]. \
    Responding to the bot or mentioning it won't have any effect.\n\n
    [peaceiris/actions-label-commenter]: https://github.com/peaceiris/actions-label-commenter
    "

labels:
