name: Stable Backport Check
on:
  issue_comment:
  pull_request_target:
    types:
      - labeled

jobs:
  check-backport:
    name: Check Backport
    if: ${{ ( github.event.issue.pull_request != '' && contains(github.event.comment.body, '@jellyfin-bot check backport') ) || github.event.label.name == 'stable backport' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify as seen
        uses: peter-evans/create-or-update-comment@v1.4.5
        if: ${{ github.event.comment != null }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          reactions: '+1'

      - name: Notify as running
        id: comment_running
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.pull_request.id }}
          body: |
            Running backport tests
          reactions: eyes
